### ISSUE TITLE
'IRISTypeCompiler' object has no attribute 'visit_timestamp'. Did you mean: 'visit_TIMESTAMP'?

### ISSUE THREAD

**Issue by k-tratseuski** [caretdev/sqlalchemy-iris#17]
Hi. I've faced an issue when tried to use alembic with iris db.
Running alembic revision --autogenerate failed because of no `visit_timestamp` in `IRISTypeCompiler`.

The example model:
```python
class Foo(Base):
    __tablename__ = "foo"
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.current_timestamp())
```

The error I receive
```bash
 sqlalchemy/sql/visitors.py", line 137, in _compiler_dispatch
    meth = getter(visitor)
           ^^^^^^^^^^^^^^^
AttributeError: 'IRISTypeCompiler' object has no attribute 'visit_timestamp'. Did you mean: 'visit_TIMESTAMP'?

The above exception was the direct cause of the following exception:

...
sqlalchemy/sql/compiler.py", line 965, in visit_unsupported_compilation
    raise exc.UnsupportedCompilationError(self, element) from err
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy_iris.base.IRISTypeCompiler object at 0x1034257c0> can't render element of type IRISTimeStamp() (Background on this error at: https://sqlalche.me/e/20/l7de)
```

Seems `IRISTypeCompiler` is missing such method

```python
def visit_timestamp(self, type_, **kw):
    return self.visit_TIMESTAMP(type_, **kw)
```

**Comment by daimor** [comment]
Can you provide a full example, I don't see any issues on SQLAlchemy-iris side, and can't reproduce it

**Comment by k-tratseuski** [comment]
> Can you provide a full example, I don't see any issues on SQLAlchemy-iris side, and can't reproduce it

I used your [template with alembic](https://github.com/caretdev/fastapi-iris-demo) to reproduce the bug

Steps to reproduce:

1. Remove the initial migration
2. Add `Datetime` field to the db model

```python

class Todo(Base):
    __tablename__ = 'todo'

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), index=True, nullable=False)
    description = Column(Text, nullable=False)
    time_created = Column(DateTime(timezone=True), server_default=func.current_timestamp())

```
3. Base is changed to have the schema configured
```python
Base: DeclarativeMeta = declarative_base(metadata=MetaData(schema="foo"))
```
4. `env.py` is changed according alembic docs to work with custom schema
```python
def include_name(name, type_, parent_names):
    if type_ == "schema":
        # NOTE: this will not include the default schema
        return name in ["foo", ]
    else:
        return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
        include_name=include_name,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_schemas=True,
            include_name=include_name,
        )

        with context.begin_transaction():
            context.run_migrations()
```
5. Generate initial migration and apply it
6. Add some field to the db model
```python
class Todo(Base):
    __tablename__ = 'todo'

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), index=True, nullable=False)
    description = Column(Text, nullable=False)
    time_created = Column(DateTime(timezone=True), server_default=func.current_timestamp())
    foo = Column(String(200), nullable=False)
```
7. Run the `alembic revision --autogenerate` command
```bash
 alembic revision --autogenerate -m "foo" 
INFO  [alembic.runtime.migration] Context impl IRISImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added column 'foo.todo.foo'
Traceback (most recent call last):
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 137, in _compiler_dispatch
    meth = getter(visitor)
           ^^^^^^^^^^^^^^^
AttributeError: 'IRISTypeCompiler' object has no attribute 'visit_timestamp'. Did you mean: 'visit_TIMESTAMP'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/config.py", line 636, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/command.py", line 236, in revision
    script_directory.run_env()
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/tkv4/Desktop/foo/fastapi-iris-demo/app/migrations/env.py", line 97, in <module>
    run_migrations_online()
  File "/Users/tkv4/Desktop/foo/fastapi-iris-demo/app/migrations/env.py", line 91, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/command.py", line 212, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/api.py", line 570, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/api.py", line 617, in _run_environment
    compare._populate_migration_script(
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 65, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 98, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/util/langhelpers.py", line 310, in go
    fn(*arg, **kw)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 137, in _autogen_for_tables
    _compare_tables(
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 262, in _compare_tables
    with _compare_columns(
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 411, in _compare_columns
    comparators.dispatch("column")(
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/util/langhelpers.py", line 310, in go
    fn(*arg, **kw)
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/autogenerate/compare.py", line 945, in _compare_type
    isdiff = autogen_context.migration_context._compare_type(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/runtime/migration.py", line 722, in _compare_type
    return self.impl.compare_type(inspector_column, metadata_column)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/sqlalchemy_iris/alembic.py", line 56, in compare_type
    return super().compare_type(inspector_column, metadata_column)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/ddl/impl.py", line 591, in compare_type
    inspector_params = self._tokenize_column_type(inspector_column)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/alembic/ddl/impl.py", line 491, in _tokenize_column_type
    definition = self.dialect.type_compiler.process(column.type).lower()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 960, in process
    return type_._compiler_dispatch(self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 139, in _compiler_dispatch
    return visitor.visit_unsupported_compilation(self, err, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkv4/Library/Caches/pypoetry/virtualenvs/test-ewoZ_pbk-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 965, in visit_unsupported_compilation
    raise exc.UnsupportedCompilationError(self, element) from err
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy_iris.base.IRISTypeCompiler object at 0x106c87ec0> can't render element of type IRISTimeStamp() (Background on this error at: https://sqlalche.me/e/20/l7de)

```

**Comment by daimor** [comment]
Thanks, I found the issue, published a new release 0.15.4, check once it will be available

**Comment by daimor** [comment]
new release available https://pypi.org/project/sqlalchemy-iris/0.15.4/

**Comment by k-tratseuski** [comment]
> new release available https://pypi.org/project/sqlalchemy-iris/0.15.4/

Thank you for the update, will check

**Comment by k-tratseuski** [comment]
> new release available https://pypi.org/project/sqlalchemy-iris/0.15.4/

Seems working, thank you!
